### ISSUE TITLE
Permettre l'ajout de text par glisser/déposer

### ISSUE THREAD

**Issue by aloisdg** [aloisdg/pointmedian#10]
Hello,

L'idée ce serait d'utiliser le drag n drop [natif](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API) pour pouvoir glisser des `txt` dans la textarea.

**Comment by KatShulu** [comment]
Hey ! 
Je ne suis pas sûre de comprendre, le drag & drop a l'air de marcher depuis un autre onglet et depuis un texte hors navigateur, peut tu m'expliquer ? 
Merci :D

**Comment by aloisdg** [comment]
Est-ce que ça marche avec un text dans un fichier text?

**Comment by KatShulu** [comment]
J'ai essayer depuis le bloc note, depuis vs code, depuis un nouvel onglet et oui le drag marche correctement

**Comment by aloisdg** [comment]
coool. bon ben je clos :p
