### ISSUE TITLE
Couleur du bouton copier 

### ISSUE THREAD

**Issue by Polibous** [aloisdg/pointmedian#12]
Je testerais une autre couleur pour le bouton copier, pour faire en sorte qu'il ressorte davantage.

**Comment by aloisdg** [comment]
Sur le bouton on peut explorer un léger effet de brillance avec: `  background-image: linear-gradient(180deg,hsla(0,0%,100%,.15),hsla(0,0%,100%,0));
}`

Est-ce souhaitable ? À discuter.

**Comment by aloisdg** [comment]
La couleur vient avec #14
