### ISSUE TITLE
Effacement du placeholder 

### ISSUE THREAD

**Issue by Polibous** [aloisdg/pointmedian#13]
Ce serait plus "UX friendly" si le placeholder disparaissait lorsque l'on commence à saisir son texte dans le field text area.

**Comment by aloisdg** [comment]
C'est à dire? Est-ce que tu penses à exemple 1 ou exemple 2? https://jsfiddle.net/d19ow74g/

**Comment by aloisdg** [comment]
La nouvelle UI possède un premier jet de cette feature. L'effacement ce fait au click sur l'area source. Je suis pas à 100% sur cette feature qui pèche possiblement un peu niveau a11y. à revoir plus tard. je clos pour le moment.

#14
