### ISSUE TITLE
Placer le text dans le <footer> dans une balise <small>

### ISSUE THREAD

**Issue by aloisdg** [aloisdg/pointmedian#15]
Hello,

L'élément HTML `<small>` permet de représenter des commentaires ou des textes à écrire en petits caractères (des termes d'un contrat, des mentions relatives au droit d'auteur, etc.) quelle que soit la présentation. Il semble sémantiquement convenir à notre usage. 

Afin de réduire la taille du footer tout en augmentant ça valeur sémantique, l'idée est de placer le text du `footer` dans un `small`. De passer de:

```html
<footer>bla blah blah</footer>
```
à

```html
<footer><small>bla blah blah</small></footer>
```

[MDN](https://developer.mozilla.org/fr/docs/Web/HTML/Element/small)

**Comment by emergenitro** [comment]
Hello!

Donc, je dois seulement changer les deux, non? Je voudrais essayer ca, s'il vous plait. 

Je suis desole parce que mon francais n'est pas tres bon. Je suis encore en train de l'apprendre. 

Merci!

**Comment by aloisdg** [comment]
@emergenitro salut! Oui bien sûr tu peux faire ça. L'idée est d'ajouter la balise `<small>` autour du contenu actuel du `<footer>` mais à l'intérieur du `footer`. Je t'assigne l'issue. Demande moi si il y a un soucis :)

**Comment by MSalmazo** [comment]
Salut! J'aimerais bien essayer celui-ci svp.

**Comment by aloisdg** [comment]
@MSalmazo cette issue a déjà été assignée.
