### ISSUE TITLE
Arrondir les boutons

### ISSUE THREAD

**Issue by aloisdg** [aloisdg/pointmedian#16]
Hello,

Afin d'améliorer l'identité du site, l'idée serait d'arrondir les angles du boutons.

Pour ça rien de plus simple avec [border-radius](https://developer.mozilla.org/fr/docs/Web/CSS/border-radius).

Passer de :

    button { border-radius: 6px; }
    
à:    

    button { border-radius: 20px; }
    
Cela devrait donner un rendu de ce genre :

![image](https://user-images.githubusercontent.com/3449303/221700091-9815e99a-03e4-439a-a475-640b47cdaeb7.png)

**Comment by emergenitro** [comment]
Hello!

Je voudrais essayer ça, s'il vous plait. Je voudrais aussi le formater un peu plus.

Merci!

**Comment by aloisdg** [comment]
Merci pour ton implication. C'est cool !

Il faudra reporter ces changements sur la nouvelle UI. Je t'invite à attendre vendredi prochain pour la suite. :)

En attendant tu peux la consulter ici: https://deploy-preview-14--pointmedian.netlify.app/

**Comment by emergenitro** [comment]
Merci! 

La nouvelle UI est super! Félicitations!

**Comment by aloisdg** [comment]
Merci ! C'est une création de @Polibous
