### ISSUE TITLE
Ajouter la balise theme-color manquante

### ISSUE THREAD

**Issue by aloisdg** [aloisdg/pointmedian#17]
Hello,

Chrome nous remonte un léger warning

![image](https://user-images.githubusercontent.com/3449303/221850468-e4cc7822-db24-4f01-88dd-9d2b219652b2.png)

transcript:

```html
Does not set a theme color for the address bar.Failures: No `<meta name="theme-color">` tag found.
```

Premièrement, ajoutez une balise meta `theme-color` à `index.html`:

```html
<head>
  …
<meta name="theme-color" media="(prefers-color-scheme: light)" content="#fff" />
<meta name="theme-color" media="(prefers-color-scheme: dark)" content="#202b38" />
  …
</head>
```
deuxièment, ajouter une propriété `theme_color` au `manifest.webmanifest` :

```json
{
  …
  "theme_color": "#202b38"
  …
}
```

Hélas le `web.manifest` ne supporte pas la préférence de thème. Il va falloir choisir un thème par défaut pour l'app. Clair ou obscure ? (mon coeur balance pour obscure mais voyons avec @Polibous).

La bonne nouvelle c'est que c'est cours de développement. J'invite à aller lire cet échange pour voir comment une fonctionnalité est créée: [ Add support for defining a theme color for both light & dark modes (prefers color scheme)](https://github.com/w3c/manifest/issues/975)

source:

* https://developer.mozilla.org/fr/docs/Web/HTML/Element/meta/name/theme-color
* https://developer.chrome.com/docs/lighthouse/pwa/themed-omnibox/?utm_source=lighthouse&utm_medium=devtools

**Comment by Lodanslhuile** [comment]
Bonjour, 

Est-ce que je peux prendre cette issue?

Bonne journée

**Comment by aloisdg** [comment]
Yes !
