### ISSUE TITLE
Renommer macOs en macOS

### ISSUE THREAD

**Issue by aloisdg** [aloisdg/pointmedian#19]
(tout est dans le titre)

**Comment by torendil** [comment]
Hello,

J'aimerais bien traiter ce sujet, est-ce que vous pouvez me l'assigner ?

Bonne journée,

**Comment by aloisdg** [comment]
Ah yes carrément !

**Comment by MSalmazo** [comment]
Je gère, envoies moi!

**Comment by aloisdg** [comment]
@MSalmazo Aie! il se trouve que cette issue a déjà été assignée. Si tu veux tu peux regarder du côté des [good first issues](https://github.com/aloisdg/pointmedian/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) ! merci pour ta motivation :)
