### ISSUE TITLE
"Source" vs "Origine" vs "Entrée" comme label pour la première zone de texte

### ISSUE THREAD

**Issue by aloisdg** [aloisdg/pointmedian#2]
Hello,

Je ne sais pas trop quelle label utiliser pour la première zone de texte. Je souhaite en tout cas garder un label pour des raisons d'accessibilité.

![image](https://user-images.githubusercontent.com/3449303/219108432-493905f1-5588-4786-b479-849b16d7868a.png)

**Comment by Polibous** [comment]
Je garderais le label avec la mention "source"

**Comment by aloisdg** [comment]
Entendu! Le code a remplacer est au niveau du label: https://github.com/aloisdg/pointmedian/blob/main/index.html#L44

**Comment by Lodanslhuile** [comment]
Bonjour, 
Est-ce que je peux m'en occuper? 
Bonne journée

**Comment by aloisdg** [comment]
Yes !
