### ISSUE TITLE
Définir la propriété display du manifest.webmanifest à 'standalone'

### ISSUE THREAD

**Issue by aloisdg** [aloisdg/pointmedian#21]
Hello,

Google Lighthouse nous fait part d'une petite erreur:

> Failure reason
> Manifest 'display' property must be one of 'standalone', 'fullscreen', or 'minimal-ui'

Actuellement nous `display` est défini à 'browser'. Il faudrait passer à 'standalone'.

Plus d'info sur:

- https://stackoverflow.com/questions/57755771/manifest-json-display-property-has-invalid-option-of-browser
- https://developer.chrome.com/docs/lighthouse/pwa/installable-manifest/

**Comment by GaetanSourisse** [comment]
Salut, 
est-ce que je peux m'en occuper?

**Comment by aloisdg** [comment]
Yes carrément
