### ISSUE TITLE
"Copier" vs "Copier le résultat" pour copier le résultat de l'automate

### ISSUE THREAD

**Issue by aloisdg** [aloisdg/pointmedian#3]
Salut,

Je fais référence à ce bouton ci :

![image](https://user-images.githubusercontent.com/3449303/219116557-3dd65f84-fd0f-405c-8f59-a7f83a2083ec.png)

**Comment by Polibous** [comment]
Très bien, comme c'est. Les choses sont claires et ne portent pas à confusion :)

**Comment by aloisdg** [comment]
Ok merci pour le retour!
