### ISSUE TITLE
Changer l'arrière-plan de la barre de défilement

### ISSUE THREAD

**Issue by emergenitro** [aloisdg/pointmedian#30]
Bonjour!

Je suggére de changer l'arrière-plan de la barre de défilement en transparente. Par example, changer de
![image](https://user-images.githubusercontent.com/49610482/222694447-64f34fc1-e71d-401d-89ba-38656b389ecc.png)
à
![image](https://user-images.githubusercontent.com/49610482/222694382-6bcfc031-4733-4fa3-a3f3-5d9d81f62a7d.png)

Ce n'est pas une grande différence mais c'est plus joli.

Si c'est bon, puis-je essayer cette issue?

Merci!

**Comment by emergenitro** [comment]
C'est bon, ce n'est pas une grande difference. C'est en haut à droite (l'arrière-plan de la barre de défilement qui est aussi à droite).

**Comment by aloisdg** [comment]
Je n'ai pas d'avis tranché pour le moment. Qu'en penses tu @Polibous ?
